#!/bin/bash
set -e

echo "🔄 Generating Ansible inventory from Terraform outputs..."

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# Get absolute paths
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "📁 Project root: $PROJECT_ROOT"

# Set absolute paths
TERRAFORM_DIR="$PROJECT_ROOT/terraform"
ANSIBLE_DIR="$PROJECT_ROOT/ansible"
INVENTORY_FILE="$ANSIBLE_DIR/inventories/demo/hosts.yml"
VAULT_FILE="$ANSIBLE_DIR/inventories/demo/group_vars/vault.yml"
API_GROUP_VARS="$ANSIBLE_DIR/inventories/demo/group_vars/api_servers.yml"

echo "📁 Terraform dir: $TERRAFORM_DIR"
echo "📁 Ansible dir: $ANSIBLE_DIR"
echo "📁 Inventory file: $INVENTORY_FILE"
echo ""

# Verify directories exist
if [ ! -d "$TERRAFORM_DIR" ]; then
    echo -e "${RED}❌ Terraform directory not found${NC}"
    exit 1
fi

if [ ! -d "$ANSIBLE_DIR" ]; then
    echo -e "${RED}❌ Ansible directory not found${NC}"
    exit 1
fi

# Navigate to terraform directory
cd "$TERRAFORM_DIR"

# Get outputs from Terraform
echo "🔍 Getting Terraform outputs..."
UI_IP=$(terraform output -raw ui_server_public_ip 2>/dev/null || echo "")
API_IP=$(terraform output -raw api_server_public_ip 2>/dev/null || echo "")
SSH_KEY=$(terraform output -raw ssh_key_file 2>/dev/null || echo "")

# Get private IP from state
API_PRIVATE_IP=$(terraform state show 'module.compute.aws_instance.api_server' 2>/dev/null | grep 'private_ip ' | awk '{print $3}' | tr -d '"')

# Get RDS endpoint (remove port :1433)
RDS_ENDPOINT=$(terraform output -raw rds_endpoint 2>/dev/null | sed 's/:1433//' | tr -d '"' || echo "")

# Validate outputs
if [ -z "$UI_IP" ] || [ -z "$API_IP" ]; then
    echo -e "${RED}❌ Could not get IPs from Terraform${NC}"
    echo "Make sure Terraform has been applied successfully"
    exit 1
fi

echo -e "${GREEN}✓${NC} UI Server IP: $UI_IP"
echo -e "${GREEN}✓${NC} API Server IP (public): $API_IP"
echo -e "${GREEN}✓${NC} API Server IP (private): $API_PRIVATE_IP"
echo -e "${GREEN}✓${NC} SSH Key: $SSH_KEY"
echo -e "${GREEN}✓${NC} RDS Endpoint: $RDS_ENDPOINT"

# Get Windows password from vault
if [ -f "$VAULT_FILE" ]; then
    WINDOWS_PASSWORD=$(grep 'vault_windows_password:' "$VAULT_FILE" | awk '{print $2}' | tr -d '"')
    echo -e "${GREEN}✓${NC} Windows password loaded from vault"
else
    echo -e "${YELLOW}⚠️${NC} Vault file not found at: $VAULT_FILE"
    WINDOWS_PASSWORD="A#nd007.XVA"
fi

# Backup existing inventory
if [ -f "$INVENTORY_FILE" ]; then
    BACKUP_FILE="$INVENTORY_FILE.backup-$(date +%Y%m%d-%H%M%S)"
    cp "$INVENTORY_FILE" "$BACKUP_FILE"
    echo -e "${GREEN}✓${NC} Backed up inventory to: $(basename $BACKUP_FILE)"
fi

# SSH key path - use absolute path for reliability
SSH_KEY_PATH="/home/ubuntu/optima-iac/terraform/${SSH_KEY}"

echo ""
echo "📝 Generating inventory..."

# Generate inventory file
cat > "$INVENTORY_FILE" << INVENTORY_EOF
---
# Auto-generated by generate-ansible-inventory.sh
# Generated at: $(date)
# DO NOT EDIT MANUALLY - Changes will be overwritten

all:
  children:
    ui_servers:
      hosts:
        ui-server:
          ansible_host: ${UI_IP}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ${SSH_KEY_PATH}
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          
    api_servers:
      hosts:
        api-server:
          ansible_host: ${API_IP}
          ansible_user: Administrator  
          ansible_password: '${WINDOWS_PASSWORD}'
          ansible_connection: winrm
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
          ansible_winrm_port: 5986
INVENTORY_EOF

echo -e "${GREEN}✅ Inventory generated successfully!${NC}"

# Update API server group variables with RDS endpoint
echo ""
echo "📝 Updating API server group variables with RDS endpoint..."

# Backup existing api_servers.yml
if [ -f "$API_GROUP_VARS" ]; then
    cp "$API_GROUP_VARS" "$API_GROUP_VARS.backup-$(date +%Y%m%d-%H%M%S)"
fi

# Generate api_servers.yml with RDS endpoint
cat > "$API_GROUP_VARS" << API_VARS_EOF
# ansible/inventories/demo/group_vars/api_servers.yml
# Auto-generated by generate-ansible-inventory.sh
# Generated at: $(date)

# API Server specific variables
dotnet_version: "7.0"
web_server: iis
app_framework: dotnet

# IIS configuration
iis_app_pool_name: "OptimaAPI"
iis_site_name: "OptimaAPI"
iis_port: 80

# .NET configuration
dotnet_environment: "Production"
dotnet_urls: "http://*:80"

# Database configuration (auto-populated from Terraform)
db_host: "${RDS_ENDPOINT}"
db_username: "admin"
db_password: "{{ vault_db_password }}"
country_code: "jp"
env_name: "demo"

# Domain configuration
domain_base: "xva-rnd.com"
ui_subdomain: "optima-jp"

# JWT Secret (from vault)
vault_jwt_secret: "{{ vault_jwt_secret | default('OptimaJWT2024SecretKeyForDemoEnvironment256Bit!!') }}"
API_VARS_EOF

echo -e "${GREEN}✅ API server group variables updated!${NC}"
echo ""
echo "📋 Summary:"
echo "  📄 Inventory: $INVENTORY_FILE"
echo "  📄 API vars: $API_GROUP_VARS"
echo "  🔗 RDS Endpoint: $RDS_ENDPOINT"
echo ""
echo "🔍 Preview:"
echo "=== Inventory ==="
cat "$INVENTORY_FILE"
echo ""
echo "=== API Server Variables ==="
cat "$API_GROUP_VARS"